AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "console-recorder"
Description: ""
Resources:
    dynamodb5639c1a:
        Type: "AWS::DynamoDB::Table"
        Properties:
            TableName: "music"
            BillingMode: "PROVISIONED"
            AttributeDefinitions:
              -
                AttributeName: "pk"
                AttributeType: "S"
              -
                AttributeName: "sk"
                AttributeType: "S"
            KeySchema: 
              - 
                AttributeName: "pk"
                KeyType: "HASH"
              - 
                AttributeName: "sk"
                KeyType: "RANGE"
            ProvisionedThroughput: 
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1
            SSESpecification: 
                SSEEnabled: false